#+TITLE: Metrik
#+STARTUP: content
#+STARTUP: latexpreview
#+STARTUP: inlineimages
#+OPTIONS: toc:nil
#+HTML_MATHJAX: align: left indent: 5em tagside: left
#+BEGIN_HTML
---
layout: page
title: Metrik
---
#+END_HTML

* Metrik/metrischer Raum

Sei $X$ eine Menge, dann heißt eine Abbildung
$d: X \times X \rightarrow \mathbb{R}_{0}^{+}$ /Metrik/ auf $X$, wenn
gilt:

1. /Bestimmtheit/: $d(x,y) = 0 \Longleftrightarrow x = y$.
2. /Symmetrie/: $\forall x,y \in X: d(x,y) = d(y,x)$
3. /Dreiecksungleichung/:
   $\forall x,y,z \in X: d(x,z) \leq d(x,y) + d(y,z)$

Das Paar $(X,d)$ heißt dann /metrischer Raum/.

* Induzierte Metrik

In einem [[norm][normierten Raum]] (d.h. einem Vektorraum auf dem eine
Norm $\|\cdot\|$ definiert ist wird durch $d(x,y) := \|(x-y)\|$ eine
Metrik $d$ induziert. $d$ heißt dann die von $\|\cdot\|$ induzierte
Metrik.

* Spezielle Metriken

** Metriken auf dem Vektorraum der reellen Zahlen

Seien $x,y \in \mathbb{R}^n$, dann heißt

-  $d_{2}(x,y) := \|x-y\|_2 = \sqrt{\sum\_{i=1}^{n} (x_i - y_i)^2}$
   /Euklidische Metrik/. Sie wird durch die [[norm][euklidische Norm]]
   induziert.
-  $d_{\infty}(x,y) := \|x-y\|\_{\infty} = \max\{|x_i - y_i| | 1 \leq i \leq n\}$
   /Maximum-Metrik/. Sie wird durch die [[norm][Maximumsnorm]]
   induziert.
-  $d_{1}(x,y) := \|x-y\|_1 = \sum\_{i=1}^{n} |x_i - y_i|$ heißt
   $l_i$-/Metrik/. Sie wird durch die [[norm][$l_1$-Norm]] induziert.

** Metriken auf dem Vektorraum der komplexen Zahlen

-  Betragsfunktion

** Metriken auf dem Vektorraum der Binärzahlen

Sei $\mathcal{B} = \\{0,1\\}$ die Menge der binären Ziffern und sei
$b \in \mathcal{B}^n$ die Binärdarstellung einer Zahl $b \in \mathbb{N}$
mit $n \in \mathbb{N}$ Ziffern.

-  /Hamming-Abstand/: Die Abbildung
   $d: \mathcal{B}^n \times \mathcal{B}^n \rightarrow \mathbb{R}$ mit
   $d(a,b) := \sum_{i=1}{n} |a_i - b_i|$ heißt /Hamming-Abstand/. Der
   Hamming-Abstand ist die Anzahl der verschiedenen Ziffern in $a$ und
   $b$.

* Epsilon-Kugel

Sei $(X, d)$ metrischer Raum und $x \in X$ und
$\epsilon \in \mathbb{R}\_{>0}$. Dann heißt die Menge
$B_{\epsilon}(x) := \\{y \in X \mid d(x,y) < \epsilon \\}$ (offene)
$\epsilon$-/Kugel/ um $x$ mit Abstand $\epsilon$ bzgl. der Metrik $d$.

* Umgebung

In einem metrischen Raum $(X, d)$ heißt $U \subseteq X$ /Umgebung/ von
$x \in X$, wenn ein $\epsilon \in \mathbb{R}\_{>0}$ existiert mit
$B_{\epsilon}(x) \subseteq U$, d.h. wenn es eine (offene)
$\epsilon$-Kugel um $x$ gibt, die in $U$ liegt.

Wenn also $B_{\epsilon}$ (offene) $\epsilon$-Kugel um $x$ ist, dann ist
also insbesondere $B_{\epsilon}$ und jede Obermenge davon Umgebung von
$x$.

* Innerer Punkt

Sei $(X,d)$ metrischer Raum und $M \subseteq X$ eine Teilmenge. Dann
heißt ein $x \in M$ /innerer Punkt/ von $M$, wenn eine Umgebung $U$ von
$x$ existiert, sodass $U \subseteq M$.

Ein $x \in M$ ist also genau dann innerer Punkt, wenn
$\exists \epsilon > 0: \forall y \in X: d(x,y) < \epsilon \Rightarrow y \in M$
gilt.

*Eigenschaften:*

-  Wenn $U$ Umgebung von $x$ ist, dann ist $x$ innerer Punkt von $U$ und
   jeder Obermenge von $U$.

* Offene Mengen

Eine Teilmenge $M$ eines metrischen Raumes $(X,d)$ heißt /offen/, wenn
sie nur innere Punkte besitzt. Offene Mengen sind Verallgemeinerungen
offener Intervalle.

Eine Menge $M \subseteq X$ ist also genau dann offen, wenn
$\forall x \in M: \exists \epsilon > 0: \forall y \in X: d(x,y) < \epsilon \Rightarrow y \in M$
gilt.

*Eigenschaften:*

-  Beliebige (auch unendlich viele) Vereinigungen offener Mengen sind
   wieder offen.
-  Endliche Durchschnitte offener Mengen sind wieder offen.

* Abgeschlossene Mengen

Eine Teilmenge $M$ eines metrischen Raumes $(X,d)$ heißt genau dann
/abgeschlossen/, wenn ihr Komplement $X \setminus M$ offen ist.
Abgeschlossene Mengen sind Verallgemeinerungen abgeschlossener
Intervalle.

Eine Menge $M \subseteq X$ ist also genau dann abgeschlossen, wenn
$\forall x \in X \setminus M: \exists \epsilon > 0: \forall y \in X: d(x,y) < \epsilon \Rightarrow y \in X \setminus M$
gilt.

*Eigenschaften:*

-  Endliche Vereinigungen abgeschlossener Mengen sind wieder
   abgeschlossen.
-  Beliebige (auch unendliche) Durchschnitte abgeschlossener Mengen sind
   wieder abgeschlossen.

* Randpunkt

Sei $(X,d)$ metrischer Raum. Ein Punkt $x \in X$ heißt /Randpunkt/ einer
Menge $M \subseteq X$, wenn für jede Umgebung $U$ von $x$ gilt:

1. $U \cap M \neq \emptyset$ und
2. $U \cap (X \setminus M) \neq \emptyset$

Die Menge der Randpunkte wird mit $\partial M$ bezeichnet.

* Abschluss

Sei $(X,d)$ metrischer Raum. Der /Abschluss/ $\bar{M}$ einer
$M \subseteq X$ ist die kleinste abgeschlossene Menge, die $M$ enthält.
ALso gilt $\bar{M} \subseteq A$ für alle $A \subseteq X$, die
abgeschlossen sind und $M$ enthalten ($M \subseteq A$).

$M$ heißt dann /dicht/ in $\bar{M}$.

*Eigenschaften:*

-  Sei $(X,d)$ metrischer Raum und $M \subseteq X$ mit Rand
   $\partial M$, dann gilt $\bar{M} = M \cup \partial M$.

** Äquivalenz

In einer Menge $X$ heißen zwei Metriken $d_1, d_2$ äquivalent, wenn sie
die gleichen offenene Mengen generieren.

*Eigenschaften:*

-  Zwei Metriken $d_1, d_2$ auf $X$ sind äquivalent, wenn es
   $c_1, c_2 \in \mathbb{R}\_{>0}$ gibt, sodass
   $\forall x,y \in X: c_{1}d_{1}(x,y) \leq d_{2}(x,y) \leq c_{2}d_{1}(x,y)$
   gilt.
