#+TITLE: Gnfa
#+STARTUP: content
#+STARTUP: latexpreview
#+STARTUP: inlineimages
#+OPTIONS: toc:nil
#+HTML_MATHJAX: align: left indent: 5em tagside: left
#+BEGIN_HTML
---
layout: page
title: Gnfa
---
#+END_HTML

* Generalisierte Nicht-deterministische Automaten

Ein /generalisierter endlicher nicht-deterministischer Automat/ (engl.
/generalized non-deterministic finite automaton/; GNFA) ist ein 5-Tupel
$M := (Q,\Sigma, \delta, q, p)$ mit:

-  einer endlichen /Zustandsmenge/ $Q$
-  einem Alphabet $\Sigma$
-  einer Transitionsfunktion
   $\delta: Q\setminus\{p\} \times Q\setminus\{q\} \rightarrow \mathcal{R}$
   (von jedem Zustand zu jedem Zustand gibt es genau eine Kante, die mit
   einem regulären Ausdruck $\mathcal{R}$ beschriftet ist, ggf. mit
   $\emptyset$, aber keine *in* den Anfangszustand und keine *aus* dem
   Endzustand).
-  *genau einem* Anfangszustand $q \in Q$
-  *genau einem* Endzustand $p \neq q$, der vom Anfangszustand
   verschieden ist

*Vorgehen um aus einem NFA einen GNFA zu machen:*

-  Führe einen neuen Anfangszustand $q'$ ein und eine
   $\epsilon$-Transition von dort zum alten Anfangszustand $q$.
-  Führe einen neuen Endzustand $p$ ein und von allen alten Endzuständen
   eine $\epsilon$-Transition nach $p$. Wähle dann $p$ als Endzustand
   des GNFA.
-  Führe von jedem Zustand $q_1$ zu jedem Zustand $q_2$ genau eine Kante
   ein.

   -  Wenn es vorher genau eine Kante von $q_1$ nach $q_2$ gab, dann
      verwende diese Kante unverändert.
   -  Wenn es vorher mehr als eine Kante von $q_1$ nach $q_2$ gab, dann
      entferne diese und verwende als Beschriftung für die neue Kante
      zwischen $q_1$ und $q_2$ die Vereinigung der alten
      Kantenbeschriftungen
   -  Wenn es vorher keine Kante von $q_1$ nach $q_2$ gab, dann
      Beschrifte die neue Kante mit $\emptyset$.

*Vorgehen um aus einem GNFA einen regulären Ausdruck zu machen:*

Eliminiere iterativ Zustände $q \in Q$, bis $Q$ nur noch zwei Zustände
(den Anfangs und den Endzustand enthält). Die verbleibende Kante ist
dann mit dem gesuchten regulären Ausdruck beschriftet. Bilde also in
jeder Iteration $Q'$ und $\delta'$ mit:

-  $Q' = Q\setminus\{q\}$
-  $\delta'(q_1, q_2) = \delta(q_1, q_2) \cup \delta(q_1, q) (\delta(q, q))^* \delta(q, q_2)$
   für alle $q_1, q_2 \in Q'$
