#+TITLE: Autonome Systeme
#+STARTUP: content
#+STARTUP: latexpreview
#+STARTUP: inlineimages
#+OPTIONS: toc:nil
#+BEGIN_HTML
---
layout: page
title: Autonome Systeme
---
#+END_HTML

Ein *Autonomes System* (AS) ist eine Gruppe von IP Netzen, die gemeinsam
verwaltet werden. AS sind untereinander verbunden und bilden so das
Internet. AS werden über eine 16-Bit (RFC1930) oder eine 32-Bit Zahl
(RFC6996) identifiziert, welche von der IANA vergeben wird.

* Arten

- *Stub-AS* sind mit /genau/ einem anderen AS über eine direkte Leitung
  verbunden. Sie können nur über diese Direktverbindung Daten mit dem
  anderen AS und dem Rest des Internets austauschen
- *Multihomed AS* sind mit mindestens zwei anderen AS über eine direkte
  Leitung verbunden
- *Transit-AS* sind mit mindestens zwei andere AS angebunden und
  fungieren als Verbindung zwischen den angeschlossenen AS, d.h. sie
  leiten Daten von den angeschlossenen AS an andere angeschlossene AS
  weiter. Die Internet-Backbone-Netzwerke sind typische Beispiele für
  Transit-AS.

* Gründe für die Verwendung von AS

1. *Administrative Autonomität*:
   - Routing Policies können individuell für jedes AS festgelegt werden
   - Protokolle können individuell für jedes AS festgelegt werden
2. *Skalierung*: AS ermöglichen weitere Aggregation von Routing
   Information (d.h. kleine routing tabellen), da beim interdomain
   routing nur gespeichert werden muss, zu welchem AS eine IP Adresse
   gehört. Die Weiterleitung des IP-Pakets an den Host übernimmt dann
   das AS. Bei einem flachem Netzwerk müsste jeder Router für jedes
   IP-Netz einen Eintrag haben, der angibt, wohin ein IP-Paket zu
   senden ist.
