#+TITLE: Gruppe
#+STARTUP: content
#+STARTUP: latexpreview
#+STARTUP: inlineimages
#+OPTIONS: toc:nil
#+HTML_MATHJAX: align: left indent: 5em tagside: left
#+BEGIN_HTML
---
layout: page
title: Gruppe
---
#+END_HTML

* Gruppen

Eine /Halbgruppe/ ist ein Paar $(G,\ast)$ aus einer nichtleere Menge $G$
und einer Verknüpfung $\ast: G \times G \rightarrow G$ auf dieser Menge,
für die gilt:

1. Assoziativgesetz bzgl. "$\ast$", d.h.
   $\forall a,b,c \in G: (a \ast b) \ast c = a \ast (b \ast c)$

Gilt außerdem:

2. es gibt ein neutrales Element $e_{\ast}$ bzgl. "$\ast$", d.h.
   $\exists e_{\ast} \in G: \forall a \in G: a \ast e_{\ast} = e_{\ast} \ast a = a$
3. es gibt inverse Elemente bzgl. "$\ast$", d.h.
   $\forall a \in G: \exists inv_{\ast}(a) \in G: a \ast inv_{\ast}(a) = e_{\ast}$

dann heißt das Paar $(G,\ast)$ /Gruppe/.

Gilt außerdem:

4. Kommutativgesetz bzgl. "$\ast$", d.h.
   $\forall a,b \in G: (a \ast b) = (b \ast a)$

dann heißt das Paar $(G,\ast)$ /kommutative/ oder /abelsche Gruppe/.

Ist $G$ endliche Menge, dann heißt $(G,\ast)$ auch /endliche Gruppe/.

*Eigenschaften:*

-  In einer Gruppe oder einer kommutativen Gruppe sind Links- und
   Rechtsinverse Elemente identisch. Es gilt also:
   $\forall a \in G: \exists inv_{\ast}(a) \in G: a \ast inv_{\ast}(a) = inv_{\ast}(a) \ast a = e$
-  Das neutrale Element einer Gruppe $(G,\ast)$ ist eindeutig, d.h. ...
-  Das Inverse Element zu einem Element $a \in G$ ist eindeutig, d.h.
   ...
-  Das Inverse des neutralen Elements ist das neutrale Element. Sei
   $e \in G$ das netrale Element der Gruppe $(G,\ast)$, dann gilt
   $inv_{\ast}(e) = e$.
-  Sei $(G,\ast)$ eine endliche Gruppe mit neutralem Element $e_{\ast}$,
   dann gilt $\forall a \in G: a^{|G|} = e_{\ast}$.

* Untergruppe

Sei $(G,\ast)$ eine Gruppe und $U \subseteq G$. Dann heißt $(U,\ast)$
/Untergruppe von/ $G$, wenn gilt:

-  $\ast$ ist in $U$ abgeschlossen, d.h.
   $\forall a,b \in U: a \ast b \in U$
-  inverse Elemente sind in $U$, d.h.:
   $\forall a \in U: inv_{\ast}(a) \in U$

*Eigenschaften:*

-  Sei $e$ neutrales Element der Gruppe $(G,\ast)$ und sei $(U,\ast)$
   Untergruppe von $G$, dann gilt $e \in U$.
-  /Satz von Lagrange/: Sei $(U,\ast)$ Untergruppe der endlichen Gruppe
   $(G,\ast)$. Dann gilt $|U| | |G|$

* Homomorphismus/Isomorphismus

Eine Abbildung $f: G_1 \rightarrow G_2$ zwischen zwei Gruppen
$(G_1,\ast)$ und $(G_2, +)$ heißt /(Gruppen-) Homomorphismus/, wenn
$\forall a,b \in G_1: f(a \ast b) = f(a) + f(b)$ gilt.

Ist $f$ [[bijektiv]] so heißt $f$ /(Gruppen-) Isomorphismus/ und $G_1$
und $G_2$ heißen /isomorph/ (oder auch /Isomorphismen/).

*Eigenschaften:*

-  Sei $e_1 \in G_1$ das neutrale Element der Gruppe $(G_1, \ast)$ und
   $\e_2 \in G_2$ das neutrale Element $(G_2, +)$, dann gilt für alle
   Homomorphismen $f: G_1 \rigtharrow G_2$:

   -  das neutrale Element wird auf das neutrale Element abgebildet,
      d.h. $f(e_1) = e_2$
   -  das Bild eines inversen Elements ist die inverse des Bildes, d.h.
      $\forall a \in G_{1}: f(inv_{\ast}(a)) = inv_{\ast}(f(a))$

-  Gruppen mit einem Element $|G| = 1$ sind isomorph zu
   $G = \\{e_{\ast}\\}$.
-  Gruppen mit zwei Elementen $|G| = 2$ sind isomorph zu
   $\mathbb{Z}_{2}$.
-  Gruppen mit drei Element $|G| = 3$ sind isomorph zu $\mathbb{Z}_{3}$.

* zyklische Gruppen

Eine Gruppe $(G,\ast)$ heißt /zyklisch/, wenn es ein $a \in G$ und ein
$n \in \mathbb{N}$ gibt, sodass
$G = \\{a^i | i \in \mathbb{N}\_{\leq n} \\}$ gilt, wobei wir $a^n$
definieren als:

$$a^n := \begin{cases}
a & \text{falls } n = 1\\
a^{n-1} \ast n & \text{falls } n > 1\\
\end{cases}$$

$a$ heißt dann auch /erzeugendes Element/ der Gruppe.

*Eigenschaften:*

-  Sei $(G,\ast)$ eine zyklische Gruppe mit $n \in \mathbb{N}$ Elementen
   und erzeugendem Element $a \in G$, dann gilt für das neutrale Element
   der Gruppe $e_{\ast} = a^n$.

* Permutationsgruppe

TODO
