#+TITLE: Sorten
#+STARTUP: content
#+STARTUP: latexpreview
#+STARTUP: inlineimages
#+OPTIONS: toc:nil
#+BEGIN_HTML
---
layout: page
title: Sorten
---
#+END_HTML

*Sorten* kann man sich wie Datentypen von Programmiersprachen
vorstellen. Sorten schreiben wir mit großem Anfangsbuchstaben, z.B.
$\text{Number}$.

* Sortenmenge

Eine nichtleere Menge von Sorten $S = \{s_0, s_1,\dots\}$ heißt /Sortenmenge/.
Die Elemente von $S$ heißen /Sorten/.

Mengenoperationen auf sortierten Mengen zur selben Sortenmenge werden
sortenweise auf die Elemente der sortierten Mengen übertragen, d.h. es
gilt z.B.:

$\{M_s\}_{s\in S} \cap \{N_s\}_{s \in S} := \{M_s \cap N_s\}_{s\in S}$

** Einsortigkeit

Enthält eine Sortenmenge $S$ lediglich ein Element, so spricht man von
*Einsortigkeit*. Das eizige Element von $S$ wird dann mit $s$ bezeichnet.

* S-sortierte Menge

Eine $S$-sortiert Menge $M$ ist eine Menge von *nichtleeren* Mengen, in
der jede nicht-leeren Menge einer Sorte der Sortenmenge $S$ zugeordent
werden kann. Wir sagen die Elemtente von $M$ können mit den Elementen
von $S$ *indiziert* werden und schreiben $M = \{M_s\}_{s\in S}$, wobei
$M_s \neq \emptyset$ für jedes $s\in S$ gilt.
